### ISSUE TITLE
Cannot edit admin message

### ISSUE THREAD

**Issue by chicuong2412** [WinfXK/Knickers#4]
I translated all Chinese text into my language in the message.yml file (and saved it).
But when it came to the game, it was all Chinese, only the words that were passed in '' would change to my language.

**Comment by WinfXK** [comment]
Key of data is not directly translated, right? You can see if it is overwritten. I wrote a function to detect that the required text does not exist or the type mismatch will directly overwrite. If there is a need, I can directly produce a multilingual version. What language do you need? By the way, my English is not good. Don't laugh at me.

**Comment by chicuong2412** [comment]
I am using Vietnamese language. I hope you can help me. And by the way, my English is not very good.

**Comment by chicuong2412** [comment]
I also did not translate the keyword part of the data.

**Comment by WinfXK** [comment]
Can I have a look at your revised document? Let me see what's wrong. If it's convenient, you can send it directly to my email: Winfxk@qq.com?

**Comment by chicuong2412** [comment]
I am sincerely sorry I do not have a QQ account, please see it here: [](https://pastebin.com/3EkWUxvK)

**Comment by chicuong2412** [comment]
https://pastebin.com/3EkWUxvK

**Comment by WinfXK** [comment]
It doesn't matter, but I don't have time now. Can I reply to you in 3 to 4 hours?

**Comment by chicuong2412** [comment]
Of course it's okay, no problem at all

**Comment by chicuong2412** [comment]
And by the way, can you support PlaceholderAPI?

**Comment by WinfXK** [comment]
By the way, the text that non ordinary players (OP or knickers administrators) can see cannot be modified through message.yml! Of course, I will implement all customizable in the future.

**Comment by WinfXK** [comment]
I'm sorry! I don't even know what it is! Because I haven't interacted with everybody for a long time! Knickers was also a player who suggested that I write it.

**Comment by chicuong2412** [comment]
I look forward to the next update, the text the admin can see can be changed. That will help Knicker will be more people use.

**Comment by WinfXK** [comment]
:), I was lazy at that time. Maybe I will integrate some common languages into knickers for quick use

**Comment by chicuong2412** [comment]
You can take a look at it https://nukkitx.com/resources/placeholderapi.104/

**Comment by WinfXK** [comment]
I often can't open nukkitx's web page. Been checking my browser

**Comment by chicuong2412** [comment]
1. getting API instance
CODE (JAVA):HIDE

//in java
PlaceholderAPI api = PlaceholderAPI.getInstance();
 
2. Obtaining a placeholder value
There a a few ways how to do that

CODE (JAVA):HIDE

//getting single placeholder value
api.getValue(placeholderName, player); //player is optional and has an effect only for visitor sensitive placeholders

//getting placeholdered string containing X placeholders
api.translateString(inputString, player); //player is again optional for static placeholders

**Comment by chicuong2412** [comment]
Here is its source code on github. https://github.com/Creeperface01/PlaceholderAPI-nukkit

**Comment by WinfXK** [comment]
Thank you! I'll deal with the language first, and then I'll connect with the placeholder API

**Comment by WinfXK** [comment]
In fact, if it is convenient, it's better to register a QQ. What problems can be directly reflected in the communication group (although there are no people in the communication group)🙁

**Comment by chicuong2412** [comment]
I really thank you for your help. You are a great developer. Sorry for bothering you. I will close this issue. Please review the api in the closed issue. Wish you a good day.

**Comment by chicuong2412** [comment]
I will create a QQ account when I finish the exam. I was in the sprint stage of the competition, which gave me no time to study JAVA, even though I really wanted to.

**Comment by WinfXK** [comment]
😊I wish you success! Refueling💪

**Comment by chicuong2412** [comment]
Thank you very much.

**Comment by chicuong2412** [comment]
hey do you have wechat account?

**Comment by WinfXK** [comment]
Yes.I have WeChat, although I don't use it very often.

**Comment by chicuong2412** [comment]
I try to create a account QQ, but it only shows "Sorry, sever is busy" bla bla

**Comment by WinfXK** [comment]
Haha, maybe we can use WeChat to communicate?Of course, I can also directly register a QQ account for you.

**Comment by chicuong2412** [comment]
Thank you

**Comment by chicuong2412** [comment]
Or we can use the discord

**Comment by WinfXK** [comment]
I have registered a QQ account for you, you can log in it directly!The password is your current GitHub account nickname. Of course, I suggest you change your password after you log in!

The QQ registered for you is: 1424655603

**Comment by chicuong2412** [comment]
wait how to activate account QQ, it only show server is busy

**Comment by WinfXK** [comment]
Maybe the QQ server has exploded :)

By the way ,I've given up!Even if I use a VPN, I still can't access NukkitX's website.

**Comment by chicuong2412** [comment]
Try using a different browser software

**Comment by chicuong2412** [comment]
I was able to access the QQ email

**Comment by chicuong2412** [comment]
let's talk in QQ email

**Comment by WinfXK** [comment]
OK！My E-mail:Winfxk@qq.com

**Comment by WinfXK** [comment]
That may not be so bad!I've already opened NukkitX's page :)!But I still don't know why I can't open it so often (:

**Comment by chicuong2412** [comment]
I've experienced this, try changing devices or changing browsers.

**Comment by chicuong2412** [comment]
I sent you a message on QQ email

**Comment by WinfXK** [comment]
OK! I have received it. Let's communicate through QQ email ：）

**Comment by chicuong2412** [comment]
Hey, i can't join my qqmail. It required me to authenticate, by sending a code via the phone number corrected my id. @WinfXK
