### ISSUE TITLE
如何才能把进服之后给钟的功能关闭

### ISSUE THREAD

**Issue by asforest** [WinfXK/Knickers#5]
能不能把进服之后给钟的功能关闭，每次进服后都会发一个钟，即使设置了不经常也还是不行，每次死亡后也还是会获得一个钟

**Comment by WinfXK** [comment]
本来的设计师将工具ID设置为Null即可，但是写着写着自己给忘了，等3.0修复吧

**Comment by asforest** [comment]
支持大佬，坐等3.0发布
