### ISSUE TITLE
使用1.16版本核心启动服务器时，插件会出现严重错误

### ISSUE THREAD

**Issue by nyancatda** [WinfXK/Knickers#6]
希望您还在维护这个插件
使用1.16版本核心启动服务器，菜单物品点地后无响应，同时后台会报错

**Comment by WinfXK** [comment]
可以发下你的报错吗？另外这个插件已经更新到3.0，但是数据和原来的无法通用，所以我问下你能不能发一些你的菜单数据给我做数据同步

**Comment by nyancatda** [comment]
> 可以发下你的报错吗？另外这个插件已经更新到3.0，但是数据和原来的无法通用，所以我问下你能不能发一些你的菜单数据给我做数据同步

我使用的是GitHub上的2.1.5版本
请问你需要哪一方面的数据，我回头和报错截图一起给你

**Comment by WinfXK** [comment]
“使用1.16版本核心启动服务器时，插件会出现严重错误”这个，另外数据最好是全部，最好包括全部按钮哈哈

**Comment by nyancatda** [comment]
您好，抱歉让你久等了
1.以下是错误信息的截图，GitHub我这边图片一直传不上去就直接发网盘链接了
https://cloud.nyan.xyz/#/s/G6DcY
在菜单物品点地时后台触发的报错，游戏内不会出现菜单页面，输入"/菜单"可以正常打开菜单
2.以下是你需要的旧版本数据，图片是游戏内按钮截图，文件是配置文件，配置文件去除了执行指令，去除了服务器名字内容，子菜单只保留了一个供参考
https://cloud.nyan.xyz/#/s/BBZHM

如果还有需要的信息请回复我，我看到邮件会尽快回复
