### ISSUE TITLE
吞物品BUG

### ISSUE THREAD

**Issue by gougocoffee** [WinfXK/Knickers#7]
从第一格移动会拦截事件，移动至第一格不会。
建议：玩家拿起【快捷菜单】就应该给他关掉UI，箱子，背包，熔炉各种UI都应该关闭掉。物品移动到【快捷菜单】卡槽应该玩家的操作。

**Comment by WinfXK** [comment]
已在[v2.2.2](https://github.com/WinfXK/Knickers/releases/v2.2.2)修复，请尝试下载新版本来查看是否修复该问题，另外使用新版本请注意备份数据，因为更新造成的一切数据损失概不负责
